---
- name: Copy backend Tar
  copy:
    src: "files/artifact.tar.gz"
    dest: "/home/ubuntu/artifact.tar.gz"

- name: Extract backend
  shell: |
    tar -xzf /home/ubuntu/artifact.tar.gz /home/ubuntu
- name: Executing node
  shell: |
    cd ~/home/ubuntu/backend 
    npm install
    pm2 stop default
    pm2 start npm -- start  